replicaCount: 2

image:
  repository: local-registry:5000/mcp-registry
  tag: "latest"
  pullPolicy: IfNotPresent

env:
  - name: MCP_REGISTRY_DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: mcp-registry-db-postgres
        key: uri
  - name: MCP_REGISTRY_METRICS_ENABLED
    value: "true"
  - name: VECTORIZE_URL
    value: http://ollama.mcp.svc.cluster.local:11434
  - name: VECTORIZE_API_KEY
    valueFrom:
      secretKeyRef:
        name: mcp-vectorize
        key: apiKey
  - name: VECTORIZE_MODEL
    value: nomic-embed-text

migrations:
  enabled: true
