replicaCount: 1

image:
  repository: oci-registry-distribution.oci.svc.cluster.local:5000/registry
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  qdrantHost: "qdrant"
  qdrantPort: 6334
  qdrantAPIKey: ""
  qdrantCollection: mcp_tools
  embeddingDim: 1536
  defaultVisibility: public
  httpAddress: ":8080"
  vectorizeURL: "http://ollama.mcp.svc.cluster.local:11434"
  vectorizeAPIKey: ""
  vectorizeModel: nomic-embed-text

resources: {}

affinity: {}
nodeSelector: {}
tolerations: []
