{{/*
Expand the name of the chart.
*/}}
{{- define "distribution.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Name for registry configuration ConfigMap.
*/}}
{{- define "distribution.configName" -}}
{{- printf "%s-config" (include "distribution.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Name for autogenerated htpasswd secret.
*/}}
{{- define "distribution.htpasswdSecretName" -}}
{{- printf "%s-htpasswd" (include "distribution.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Name for the PersistentVolumeClaim.
*/}}
{{- define "distribution.pvcName" -}}
{{- printf "%s-data" (include "distribution.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Render htpasswd file content from values.
*/}}
{{- define "distribution.htpasswdContent" -}}
{{- $entries := list -}}
{{- range $entry := .Values.auth.htpasswd.entries | default list -}}
{{- $entries = append $entries (printf "%s:%s" $entry.username $entry.passwordHash) -}}
{{- end -}}
{{- join "\n" $entries -}}
{{- end -}}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "distribution.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "distribution.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "distribution.labels" -}}
helm.sh/chart: {{ include "distribution.chart" . }}
{{ include "distribution.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "distribution.selectorLabels" -}}
app.kubernetes.io/name: {{ include "distribution.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "distribution.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "distribution.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
