{{- if and .Values.auth.htpasswd.enabled (not .Values.auth.htpasswd.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "distribution.htpasswdSecretName" . }}
  labels:
    {{- include "distribution.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.htpasswd.filename }}: {{ include "distribution.htpasswdContent" . | b64enc }}
  {{- $entries := .Values.auth.htpasswd.entries | default list }}
  {{- if gt (len $entries) 0 }}
  username: {{ (index $entries 0).username | b64enc }}
  {{- with (index $entries 0).password }}
  password: {{ . | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
