apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers
  namespace: oci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers
  namespace: oci
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["create", "get", "list"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns/status"]
    verbs: ["get"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggertemplates", "triggerbindings", "triggers", "interceptors"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-oci
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clusterinterceptors", "clustertriggerbindings"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers
  namespace: oci
subjects:
  - kind: ServiceAccount
    name: tekton-triggers
    namespace: oci
roleRef:
  kind: Role
  name: tekton-triggers
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-oci
subjects:
  - kind: ServiceAccount
    name: tekton-triggers
    namespace: oci
roleRef:
  kind: ClusterRole
  name: tekton-triggers-oci
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitea-push-main
  namespace: oci
spec:
  params:
    - name: repoName
      value: $(body.repository.name)
    - name: repoUrl
      value: $(body.repository.clone_url)
    - name: imageTag
      value: $(extensions.shortSha)-$(extensions.timestamp)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: git-image-build-template
  namespace: oci
spec:
  params:
    - name: repoName
    - name: repoUrl
    - name: imageTag
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: git-image-build-
      spec:
        taskRunTemplate:
          serviceAccountName: tekton-image-builder
        pipelineRef:
          name: git-image-build
        params:
          - name: repo_url
            value: $(tt.params.repoUrl)
          - name: repo_name
            value: $(tt.params.repoName)
          - name: image_tag
            value: $(tt.params.imageTag)
        workspaces:
          - name: source
            emptyDir: {}
          - name: dockerconfig
            secret:
              secretName: oci-registry-distribution-dockerconfig
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitea-image-listener
  namespace: oci
spec:
  serviceAccountName: tekton-triggers
  resources:
    kubernetesResource:
      serviceType: ClusterIP
  triggers:
    - name: gitea-main-image-build
      serviceAccountName: tekton-triggers
      interceptors:
        - ref:
            kind: ClusterInterceptor
            name: cel
          params:
            - name: filter
              value: |
                body.ref == 'refs/heads/main'
            - name: overlays
              value:
                - key: shortSha
                  expression: body.after.substring(0,7)
                - key: timestamp
                  expression: body.head_commit.timestamp.replace("-", "").replace(":", "").replace("T", "").replace("Z", "")
      bindings:
        - ref: gitea-push-main
      template:
        ref: git-image-build-template
