{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ksyncer.fullname" . }}
  labels:
    {{- include "ksyncer.labels" . | nindent 4 }}
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["services/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["events", "namespaces"]
    verbs: ["create", "get", "list", "watch"]
{{- end }}
