{{- if and .Values.secret.enabled .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "registry.name" . }}
    helm.sh/chart: {{ include "registry.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
