{{- if .Values.metrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}-metrics
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgres.name" . }}-metrics
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postgres.name" . }}-metrics
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: exporter
          image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgres.fullname" . }}
                  key: exporter-dsn
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
{{- end }}
