replicaCount: 1

image:
  repository: qdrant/qdrant
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 6333
  grpcPort: 6334

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 20Gi

gpu:
  enabled: false
  count: 1

resources:
  limits: {}
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
