{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-db
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.env.DB_PASSWD | default "" | quote }}
{{- end }}
