apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: math
  namespace: default
  labels:
    function.knative.dev: "true"
    function.knative.dev/name: math
    function.knative.dev/runtime: go
spec:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: math
        dapr.io/app-port: "8080"
        dapr.io/metrics-port: "9092"
        description: "Greets the caller in their preferred language."
        inputs: '[{"name":"user","type":"string","required":true}]'
        outputs: '[{"name":"greeting","type":"string"}]'
    spec:
      containers:
        - name: user-container
          image: 10.96.27.199:5000/math:0000000-0 # {"$imagepolicy": "flux-system:math-policy"}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            seccompProfile: { type: RuntimeDefault }
          readinessProbe:
            httpGet: { path: /health/readiness, port: 0 }
          livenessProbe:
            httpGet: { path: /health/liveness, port: 0 }
      imagePullSecrets:
        - name: oci-registry-distribution-dockerconfig
